spring:
  profiles:
    active: test

---
spring:
  config:
    activate:
      on-profile: local
  jackson:
    property-naming-strategy: 'com.fasterxml.jackson.databind.PropertyNamingStrategies.SnakeCaseStrategy'
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:localdb
    username: sa
    password:
  h2:
    console:
      enabled: true
solvedAc:
  group:
    id: 194

---
spring:
  config:
    activate:
      on-profile: test
  jackson:
    property-naming-strategy: 'com.fasterxml.jackson.databind.PropertyNamingStrategies.SnakeCaseStrategy'
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  h2:
    console:
      enabled: true
solvedAc:
  group:
    id: 194

---
spring:
  config:
    activate:
      on-profile: remote
  jackson:
    property-naming-strategy: 'com.fasterxml.jackson.databind.PropertyNamingStrategies.SnakeCaseStrategy'
  datasource:
    url: jdbc:mysql://localhost:3306/ku_solved_ac?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: zeratul1
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      schema-locations: classpath*:schema.sql
      enabled: true
solvedAc:
  group:
    id: 194